POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer

{
    "author": "Kristian Hannula",
    "url": "https://www.kristianhannula.com/",
    "title": "My personal website and blog"
}