POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyaXN0aWFuLmhhbm51bGFAcHJvdG9uLm1lIiwiaWQiOjEsImlhdCI6MTcwMDA3MDg3N30.eyX8IKv2X9_2Kog0XI4EtrhhiMUUz6cmoLGiZ2vC-nI

{
    "author": "Kristian Hannula",
    "url": "https://www.kristianhannula.com/",
    "title": "My personal website and blog"
}